name: Create Branch For Issue
on:
  issues:
    # 이슈 담당자존재할때, 오픈, 재오픈 할때 이벤트 발생
    types: [assigned, opened, reopened]
  issue_comment:
    # 이슈 코멘트가 생성될때
    types: [created]
  pull_request:
    # PR이 닫혀있을 때
    types: [closed]
    branches:
      - develop
      - 'feature/issue-**'

env:
  user: loveAlakazam
  project_id: 2

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      # 브랜치 생성
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 이슈의 현재진행상태를 Todo 상태로 이동시킨다.
      - name: Moving assigned issues on project boards
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          user: ${{env.user}}
          project_id: ${{env.project_id}}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Todo
