name: Create Branch For Issue
on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]
    branches:
      - master
      - develop
      - 'feature/issue-**'

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      # 브랜치 생성
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # issue status
      - name: Moving assigned issues on project boards
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: My_AccountBooks
          column: Todo
          # 래포지토리 actions secret에 PERSONAL_TOKEN에 대한 시크릿값을 GITHUB_TOKEN 의 시크릿값으로 매핑
          repo-token: ${{ secrets.PERSONAL_TOKEN }}
