name: Create Branch For Issue
on:
  issues:
    types: [opened, reopened, assigned]
  pull_request:
    types: [closed]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      # 브랜치 생성
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # issue status
      - name: Moving assigned issues on project boards
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: My_AccountBooks
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
